# Generated by Django 5.1.7 on 2025-03-22 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='agenda',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('instant', 'Instant Meeting'), ('scheduled', 'Scheduled Meeting')], default='instant', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recording_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recording_file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recording_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recording_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recording_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recurrence',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='settings',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='meeting',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_url', models.URLField()),
                ('recording_type', models.CharField(choices=[('audio', 'Audio Only'), ('video', 'Video'), ('shared_screen', 'Shared Screen'), ('chat', 'Chat')], max_length=20)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='meetings.meeting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
